--- 
title: "Анализ данных для лингвистов"
author: "Г. А. Мороз"
bibliography:
- bibliography.bib
editor_options:
  chunk_output_type: console
link-citations: yes
documentclass: book
site: bookdown::bookdown_site
biblio-style: apalike
---

# О курсе

Материалы для курса Анализа данных для лингвистов, Школа лингвистики НИУ ВШЭ.

* вместо первой лекции можно посмотреть [запись лекции 2021.01.13](https://youtu.be/HmLcBJnfipk)
* вместо второй лекции можно посмотреть [запись лекции 2021.01.15](https://youtu.be/V_c_K_wBMuY)
* вместо третей лекции можно посмотреть [запись лекции 2021.01.20](https://youtu.be/cRc5z9F3XNw)
* вместо четвертой лекции можно посмотреть [запись лекции 2021.01.22](https://youtu.be/zj-1-invsGM)
* вместо пятой лекции можно посмотреть [запись лекции 2021.01.27](https://www.youtube.com/watch?v=2YRAdMLT4N0&list=PL_HB2SrKjmMJ-dUBtXUSQBZxRftJJX5uL&index=5)
* вместо шестой лекции можно посмотреть [запись лекции 2021.01.29](https://www.youtube.com/watch?v=FA-_Qbpmb6s&list=PL_HB2SrKjmMJ-dUBtXUSQBZxRftJJX5uL&index=6)
* вместо седьмой лекции можно посмотреть [запись лекции 2021.02.03](https://youtu.be/DkNnGeJT2K0)
* вместо восьмой лекции можно посмотреть [запись лекции 2021.02.05](https://youtu.be/c2mej30JnRM)
* вместо девятой лекции можно посмотреть [запись лекции 2021.02.10](https://youtu.be/9ltNRMQmt0U)
* вместо десятой лекции можно посмотреть [запись лекции 2021.02.12](https://youtu.be/zCG_edAziVk)
* вместо одиннадцатой лекции можно посмотреть [запись лекции 2021.02.19](https://youtu.be/6bERf7DMvfg)
* вместо двеннадцатой лекции можно посмотреть [запись лекции 2021.02.24](https://youtu.be/I80UaVOmpxY)
* вместо триннадцатой и четырнадцатой лекций можно посмотреть вот эти видео: [часть 1](https://youtu.be/_IltMx042DE), [часть 2](https://youtu.be/1qbk5dATogc)
* вместо пятнадцатой лекции можно посмотреть [запись лекции 2021.03.03](https://www.youtube.com/watch?v=mIhT4y4FigY&list=PL_HB2SrKjmMJ-dUBtXUSQBZxRftJJX5uL&index=12)
* вместо шестнадцатой лекции можно посмотреть
[запись лекции 2021.03.05](https://www.youtube.com/watch?v=mIhT4y4FigY&list=PL_HB2SrKjmMJ-dUBtXUSQBZxRftJJX5uL&index=12) и
[другую](https://www.youtube.com/watch?v=m06AOJBU9Bo&list=PL_HB2SrKjmMJ-dUBtXUSQBZxRftJJX5uL&index=11) и
 [третью](https://www.youtube.com/watch?v=XkEm4SHcYbg&list=PL_HB2SrKjmMJ-dUBtXUSQBZxRftJJX5uL&index=13), 
* вместо шестнадцатой лекции можно посмотреть вот это [видео](https://youtu.be/a75VjnY-w0s).

## Используемые пакеты

```{r}
packageVersion("tidyverse")
packageVersion("fitdistrplus")
packageVersion("mixtools")
packageVersion("lme4")
packageVersion("lmerTest")
packageVersion("car")
packageVersion("pscl")
packageVersion("nnet")
packageVersion("MASS")
packageVersion("ggeffects")
packageVersion("brms")
packageVersion("tidybayes")
```

## Домашние задания

* домашнее задание к лекции 23.01.2023:
    * вспомните пожалуйста, условные вероятности, формулу Байеса и при каких условиях ее применяют;
    * посмотрите освежающие материалы про [условную вероятность](http://setosa.io/conditional/) и [формулу Байеса](https://www.youtube.com/watch?v=HZGCoVF3YvM).
* [домашнее задание 1. (дедлайны: 31.01.2023 7:59, 07.02.2023 7:59)](https://classroom.github.com/a/cfoga6g-)
* [домашнее задание 2. (дедлайны: 21.02.2023 7:59, 28.02.2023 7:59)](https://classroom.github.com/a/ROIVt5jq)
* [домашнее задание 3. (дедлайны: 14.03.2023 7:59, 21.03.2023 7:59)](https://classroom.github.com/a/wZRIsza1)
